[pytest]
addopts = -p no:cacheprovider
testpaths = tests
filterwarnings =
    ignore:enable_nested_tensor is True.*norm_first was True:UserWarning
    ignore:.*PytestCacheWarning.*:pytest.PytestCacheWarning
