"""Unit tests for the foundation data pipeline modules."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.data.quality import SimHashDeduplicator, QualityScorer
from src.data.ast_filter import (
    filter_code,
    identifier_ratio,
    executable_ratio,
    is_autogenerated,
    has_one_enormous_line,
    extract_functions,
)
from src.data.function_sampler import sample_functions, is_code_empty_or_trivial
from src.data.sanity import check_packed_sample
from src.data.pipeline import pack_sequences, compute_quality_score, remove_boilerplate


def test_simhash():
    sh = SimHashDeduplicator(threshold=0.85)
    assert not sh.is_duplicate("hello world this is a test string for simhash")
    assert not sh.is_duplicate("completely different text for testing purposes")
    assert sh.is_duplicate("hello world this is a test string for simhash")
    print("SimHash: OK")


def test_quality_v2_code():
    code = 'def add(a, b):\n    """Add two numbers."""\n    result = a + b\n    return result\n\ndef subtract(a, b):\n    """Subtract."""\n    return a - b'
    score = QualityScorer.advanced_score(code, "code", "python")
    assert score > 0.2, f"code score too low: {score}"
    print(f"Quality v2 code score: {score:.3f} (OK)")


def test_quality_v2_text():
    text = "The cat sat on the mat. It was a sunny day. The birds were singing. " \
           "The wind was blowing gently through the leaves. This is a beautiful day. " \
           "The flowers are blooming beautifully in the garden. Children are playing."
    score = QualityScorer.advanced_score(text, "web_text")
    assert score > 0.1, f"text score too low: {score}"
    print(f"Quality v2 text score: {score:.3f} (OK)")


def test_ast_filter_parseable():
    code = "def foo(x, y):\n    result = x + y\n    return result\n\nprint(foo(1, 2))"
    ok, reason = filter_code(code, "python")
    assert ok, f"should be parseable: {reason}"
    print(f"AST parseable: {reason} (OK)")


def test_ast_filter_unparseable():
    ok, reason = filter_code("this is not python code at all @@@@ ### $$$ --- broken syntax", "python")
    assert not ok
    print(f"AST unparseable: {reason} (OK)")


def test_autogen_detection():
    assert is_autogenerated("Auto-generated file, do not edit")
    assert is_autogenerated("THIS CODE WAS GENERATED")
    assert not is_autogenerated("def foo(): pass")
    print("Auto-gen: OK")


def test_identifier_ratio():
    r = identifier_ratio("def foo(x, y):\n    result = x + y\n    return result")
    assert r > 0.0
    print(f"Identifier ratio: {r:.3f} (OK)")


def test_one_liner():
    assert has_one_enormous_line("x" * 600)
    assert not has_one_enormous_line("hello world this is a normal length line")
    print("One-liner: OK")


def test_executable_ratio():
    code = "def foo():\n    x = 1\n    y = 2\n    return x + y\n\n# this is a comment\n# another comment"
    r = executable_ratio(code, "python")
    assert r > 0.3, f"exec ratio too low: {r}"
    print(f"Executable ratio: {r:.3f} (OK)")


def test_packing_efficiency():
    packed, eff = pack_sequences(
        [{"input_ids": [1, 2, 3]}, {"input_ids": [4, 5]}], 10, 0
    )
    assert len(packed) == 1
    assert eff > 0.0
    print(f"Packing ({len(packed)} packs, eff={eff:.2%}): OK")


def test_packing_multiple():
    samples = [{"input_ids": [1, 2, 3]} for _ in range(5)]
    packed, eff = pack_sequences(samples, 10, 0)
    assert len(packed) >= 1
    for p in packed:
        assert len(p["input_ids"]) == 10
        assert len(p["labels"]) == 10
        assert len(p["attention_mask"]) == 10
    print(f"Packing {len(samples)} docs into {len(packed)} packs (eff={eff:.2%}): OK")


def test_function_extraction():
    code = "def foo():\n    x = 1\n    return x\n\ndef bar():\n    return 42\n\nclass Baz:\n    def method(self):\n        return 0"
    funcs = extract_functions(code, "python")
    assert len(funcs) >= 2
    print(f"Extracted {len(funcs)} functions: OK")


def test_boilerplate_removal():
    text = ("# Copyright 2023 Acme Corp\n"
            "# License: MIT\n"
            "# This file is part of Project X\n"
            "#\n"
            "print('hello world')")
    cleaned = remove_boilerplate(text)
    assert "Copyright" not in cleaned, f"Copyright still present in: {cleaned}"
    assert "print" in cleaned, f"print removed from: {cleaned}"
    print("Boilerplate removal: OK")


def test_quality_score_ranges():
    scores = []
    for cat in ["code", "web_text", "math", "books", "science", "docs", "wiki"]:
        sample = f"The quick brown fox jumps over the lazy dog. " * 10 + f"Sample {cat} " * 10
        s = compute_quality_score(sample, cat)
        scores.append(s)
    assert all(0.0 <= s <= 1.0 for s in scores), f"scores out of range: {scores}"
    print(f"Quality score ranges: all in [0,1] (OK)")


if __name__ == "__main__":
    test_simhash()
    test_quality_v2_code()
    test_quality_v2_text()
    test_ast_filter_parseable()
    test_ast_filter_unparseable()
    test_autogen_detection()
    test_identifier_ratio()
    test_one_liner()
    test_executable_ratio()
    test_packing_efficiency()
    test_packing_multiple()
    test_function_extraction()
    test_boilerplate_removal()
    test_quality_score_ranges()
    print()
    print("=" * 50)
    print("ALL TESTS PASSED")
    print("=" * 50)
